# Taskfile.yml
# 日常的なタスク管理用。初回セットアップは Makefile (make bootstrap) を使用。
version: "3"

vars:
  STOW_FLAGS: -v -t ~ --ignore='\.DS_Store$'

includes:
  link:
    taskfile: ./taskfiles/link.yml
    flatten: true
  skills:
    taskfile: ./taskfiles/skills.yml
    flatten: true
  util:
    taskfile: ./taskfiles/util.yml
    flatten: true

tasks:
  default:
    desc: 利用可能なタスク一覧を表示
    cmds:
      - task --list
