return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  opts = {
    plugins = {
      presets = {
        g = false,
      },
    },
    spec = {
      { "<leader>c", group = "コード" },
      { "<leader>m", group = "Markdown" },
      { "<leader>f", group = "検索" },
      { "<leader>g", group = "Git" },
      { "<leader>l", group = "LSP" },
      { "<leader>b", group = "バッファ" },
      { "<leader>h", group = "Git差分" },
      { "<leader>t", group = "表示切替" },
      { "<leader>x", group = "診断・リスト" },
      { "<leader>w", proxy = "<c-w>", group = "ウィンドウ" },
      { "<c-w>", group = "ウィンドウ" },
      { "<c-w>+", desc = "高さを増やす" },
      { "<c-w>-", desc = "高さを減らす" },
      { "<c-w><", desc = "幅を減らす" },
      { "<c-w>=", desc = "サイズを均等にする" },
      { "<c-w>>", desc = "幅を増やす" },
      { "<c-w>T", desc = "新しいタブへ移動" },
      { "<c-w>_", desc = "高さを最大にする" },
      { "<c-w>d", desc = "カーソル位置の診断を表示" },
      { "<c-w><c-d>", desc = "カーソル位置の診断を表示" },
      { "<c-w>h", desc = "左のウィンドウへ" },
      { "<c-w>j", desc = "下のウィンドウへ" },
      { "<c-w>k", desc = "上のウィンドウへ" },
      { "<c-w>l", desc = "右のウィンドウへ" },
      { "<c-w>o", desc = "ほかをすべて閉じる" },
      { "<c-w>c", desc = "ウィンドウを閉じる" },
      { "<c-w>q", desc = "ウィンドウを閉じる" },
      { "<c-w>s", desc = "上下に分割" },
      { "<c-w>v", desc = "左右に分割" },
      { "<c-w>w", desc = "次のウィンドウへ" },
      { "<c-w>x", desc = "次と入れ替える" },
      { "<c-w>|", desc = "幅を最大にする" },
      { "<c-w>H", desc = "ウィンドウを左端へ" },
      { "<c-w>J", desc = "ウィンドウを下端へ" },
      { "<c-w>K", desc = "ウィンドウを上端へ" },
      { "<c-w>L", desc = "ウィンドウを右端へ" },
    },
  },
  keys = {
    {
      "<leader>?",
      function() require("which-key").show({ global = false }) end,
      desc = "現在のキーマップを表示",
    },
  },
}
