# tmux エントリーポイント
# 各設定ファイルを読み込む

source-file ~/.config/tmux/conf/general.conf
source-file ~/.config/tmux/conf/keybinds.conf
source-file ~/.config/tmux/conf/pane-mode.conf
source-file ~/.config/tmux/conf/copy-mode.conf
source-file ~/.config/tmux/conf/smart-splits.conf
source-file ~/.config/tmux/conf/popup.conf
source-file ~/.config/tmux/conf/session.conf
source-file ~/.config/tmux/conf/statusbar.conf
source-file ~/.config/tmux/conf/appearance.conf
source-file ~/.config/tmux/conf/plugins.conf
